.\" man page for elmer.c
.\" Peng Gu & Xuran Wang - 10/23/2018

.TH elmer 1 "10/23/2018" "CSCI 241" "Oberlin College"

.SH NAME
.B elmer
\- read in English text from standard input and convert it into Elmer-speak

.SH SYNOPSIS
.B elmer

.SH Elmer-speak Rules
vocalised consonants [r] and [l], pronouncing them as [w] instead(from wikipedia-Elmer Fudd<Elmer-speak>)

.SH Author
Peng Gu & Xuran Wang

.SH BUGS
None so far. 
