.\" man page for izzle
.\" Peng Gu & Xuran Wang - 10/23/2018

.TH izzle 1 "10/23/2018" "CSCI 241" "Oberlin College"

.SH NAME

.B izzle
read in English from standard input and insert "-izzle" after a word's last pre-vowel consonant while discarding the remaining letters

.SH SYNOPSIS
.B izzle

.SH izzle Translation Rule
isert "-izzle" after a word's last pre-vowel consonant while discarding the remaining letters(from wikipedia-Language game)

.SH Author
Peng Gu & Xuran Wang

.SH BUGS
None so far. 
